import type { Metadata } from "next";
import { Poppins, Playfair_Display } from "next/font/google"; // Importing fonts
import "./globals.css";
import { Header } from "@/components/Headers/Header";
import { Footer } from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const playfairdisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfairdisplay.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <Toaster
          containerStyle={{ zIndex: 9999 }}
          position="top-center"
          toastOptions={{ duration: 4000 }}
        />
      </body>
    </html>
  );
}
